# Generated by Django 3.0.7 on 2020-06-08 04:05

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('seats_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_and_time_of_booking', models.DateTimeField(auto_now_add=True)),
                ('no_of_persons', models.IntegerField(verbose_name=builtins.max)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.trains')),
            ],
        ),
    ]
