# Generated by Django 3.0.7 on 2020-06-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='no_of_persons',
            field=models.IntegerField(),
        ),
    ]
