# Generated by Django 3.0.7 on 2020-06-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20200608_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='price',
            field=models.FloatField(default=120),
        ),
    ]
