# Generated by Django 3.0.7 on 2020-06-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_trains_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='train_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
