# Generated by Django 3.0.7 on 2020-06-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20200608_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='train_name',
            field=models.CharField(max_length=50),
        ),
    ]
